apiVersion: batch/v1
kind: Job
metadata:
  name: whalesay
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: whalesay
        image: rancher/cowsay
        command: ["cowsay",  "This is a Kubernetes Job!"]
      restartPolicy: Never
  backoffLimit: 4
