apiVersion: batch/v1
kind: Job
metadata:
  name: cowsay-v1-1
  namespace: default
spec:
  template:
    spec:
      completions: 10
      parallelism: 3
      containers:
      - name: cowsay
        image: rancher/cowsay
        command: ["cowsay",  "This is a Kubernetes Job!"]
      restartPolicy: Never
  backoffLimit: 4
