apiVersion: batch/v1
kind: Job
metadata:
  name: claude-code-job-v1.4
  namespace: default
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [4000]
  template:
    spec:
      containers:
      - name: claude-code
        image: ghcr.io/zeeno-atl/claude-code:latest
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-api-key
              key: key
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir code-example
            cd code-example
            echo "console.log('Hello, World')" > index.ts;
            npx  @anthropic-ai/claude-code --dangerously-skip-permissions -p "Make a basic web server that serves a simple greeter"
            cat index.ts
      restartPolicy: Never
  backoffLimit: 1
