apiVersion: batch/v1
kind: Job
metadata:
  name: claude-code-job-v1.13
  namespace: default
spec:
  parallelism: 10
  completions: 100
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 3000
        supplementalGroups: [4000]
      containers:
      - name: claude-code
        workingDir: /tmp
        image: oven/bun:debian
        env:
        - name: CONTAINER_USER_ID
          value: "1000"
        - name: CONTAINER_GROUP_ID
          value: "3000"
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-api-key
              key: key
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir code-example
            cd code-example
            echo "console.log('Hello, World')" > index.ts;
            bunx  @anthropic-ai/claude-code --dangerously-skip-permissions -p "Make a basic web server that serves a simple greeter with bun.js in index.ts"
            cat index.ts
      restartPolicy: Never
  backoffLimit: 1
